### ISSUE TITLE
Trying to figure out your code

### ISSUE THREAD

**Issue by GameModes** [tragamota/DataIntensiveSystems#1]
So I assume the scripts should be:

python data/generation/standard_route_generator.py --config data/generation/standard_route_config.json --output data/standard_routes.json

python data/generation/actual_route_generator.py --config actual_route_config.json --output data/actual_routes.json --input data/standard_routes.json --mapping ?

But as you see, I don't know where the mapping file should be or come from. Any help?

**Comment by tragamota** [comment]
Mapping is actually the ground truth of the routes, so you can actually test the performance of your solution. It can any arbitrary path on your file system.

**Comment by GameModes** [comment]
I dont really understand where I can find a ground truth of the routes and how it looks. Is it deviated from the standard_routes.json? Could you maybe send an example of such mapping file so I know what it looks like?

**Comment by tragamota** [comment]
You don't have to provide one. It generates one for you. You only need to provide a path where the script can store the ground truth json file.

CMD:
```
DataIntensiveSystems\data\generation>python actual_route_generator.py  --config actual_route_config.json --output ../actual_routes.json --input ../standard_routes.json --mapping ../ground.json
``` 

your paths might be slightly different

**Comment by GameModes** [comment]
ah I though it was an input setting, but it is a output setting. Thanks for replying so quick!
